spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/wx-order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.56.101
    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  # 公众账号, 授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付/商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://lsx888.natapp1.cc
  wechatOpenAuthorize: http://lsx888.natapp1.cc
  sell: http://lsx888.natapp1.cc
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/
server:
  servlet:
    context-path: /sell
    